package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"

	"github.com/podhmo/goat"
	"github.com/podhmo/goat/examples/enum/customtypes"
)

//go:generate goat emit -run run -initializer NewOptions main.go

// MyLocalEnum is a locally defined enum type.
type MyLocalEnum string

const (
	// LocalA is a possible value for MyLocalEnum.
	LocalA MyLocalEnum = "local-a"
	// LocalB is a possible value for MyLocalEnum.
	LocalB MyLocalEnum = "local-b"
)

var MyLocalEnumValues = []string{
	string(LocalA),
	string(LocalB),
}

// Options defines the command line options for the enum example.
type Options struct {
	// LocalEnumField demonstrates a locally defined enum.
	LocalEnumField MyLocalEnum `env:"ENUM_LOCAL_ENUM"`

	// ImportedEnumField demonstrates an enum imported from another package.
	ImportedEnumField customtypes.MyCustomEnum `env:"ENUM_IMPORTED_ENUM"`

	// OptionalImportedEnumField demonstrates an optional enum (pointer type)
	// imported from another package.
	OptionalImportedEnumField *customtypes.MyCustomEnum `env:"ENUM_OPTIONAL_IMPORTED_ENUM"`
}

// NewOptions initializes Options with default values and enum constraints.
func NewOptions() *Options {
	return &Options{
		LocalEnumField:            goat.Default(LocalA, goat.Enum(MyLocalEnumValues)),                           // Changed
		ImportedEnumField:         goat.Default(customtypes.OptionX, goat.Enum(customtypes.MyCustomEnumValues)), // Changed
		OptionalImportedEnumField: goat.Enum((*customtypes.MyCustomEnum)(nil), []customtypes.MyCustomEnum{customtypes.OptionX, customtypes.OptionY}),
	}
}

// run is the main execution logic for the enum example CLI.
// It prints the selected enum values.
func run(opts Options) error {
	fmt.Printf("Selected Local Enum: %s\n", opts.LocalEnumField)
	fmt.Printf("Selected Imported Enum: %s\n", opts.ImportedEnumField)

	if opts.OptionalImportedEnumField != nil {
		fmt.Printf("Selected Optional Imported Enum: %s\n", *opts.OptionalImportedEnumField)
	} else {
		fmt.Println("Optional Imported Enum: not set")
	}

	// Example of accessing original enum values if needed
	if opts.ImportedEnumField == customtypes.OptionX {
		fmt.Println("INFO: ImportedEnumField is OptionX")
	}

	// Example to trigger an error for testing (e.g. if a certain combination is invalid)
	// if opts.LocalEnumField == LocalA && opts.ImportedEnumField == customtypes.OptionY {
	// 	return fmt.Errorf("combination of LocalA and OptionY is not allowed")
	// }

	return nil
}

// This main function was auto-generated by goat.
func main() {
	ctx := context.Background()
	isFlagExplicitlySet := make(map[string]bool)
	var err error
	_ = err

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, `enum - run is the main execution logic for the enum example CLI.
         It prints the selected enum values.

Usage:
  enum [flags]

Flags:
  --local-enum-field             mylocalenum LocalEnumField demonstrates a locally defined enum. (default: "local-a") (env: ENUM_LOCAL_ENUM) (allowed: "local-a", "local-b")
  --imported-enum-field          mycustomenum ImportedEnumField demonstrates an enum imported from another package. (default: "option-x") (env: ENUM_IMPORTED_ENUM) (allowed: "option-x", "option-y", "option-z")
  --optional-imported-enum-field mycustomenum OptionalImportedEnumField demonstrates an optional enum (pointer type)
                                        imported from another package. (env: ENUM_OPTIONAL_IMPORTED_ENUM) (allowed: "option-x", "option-y")

  -h, --help                             Show this help message and exit
`)
	}

	// --- 1. Initialize Options Struct ---
	options := NewOptions()

	// --- 2. Process Environment Variables ---
	if localenumfieldEnvVal, ok := os.LookupEnv("ENUM_LOCAL_ENUM"); ok {
		// Environment variable for unsupported type LocalEnumField (MyLocalEnum) not handled.
	}
	if importedenumfieldEnvVal, ok := os.LookupEnv("ENUM_IMPORTED_ENUM"); ok {
		// Environment variable for unsupported type ImportedEnumField (customtypes.MyCustomEnum) not handled.
	}
	if optionalimportedenumfieldEnvVal, ok := os.LookupEnv("ENUM_OPTIONAL_IMPORTED_ENUM"); ok {
		// Environment variable for unsupported type OptionalImportedEnumField (*customtypes.MyCustomEnum) not handled.
	}

	// --- 3. Register Flags ---
	// Flag registration for unsupported type LocalEnumField (MyLocalEnum) not handled.
	// Flag registration for unsupported type ImportedEnumField (customtypes.MyCustomEnum) not handled.
	// Flag registration for unsupported type OptionalImportedEnumField (*customtypes.MyCustomEnum) not handled.

	// --- 4. Parse Flags ---
	flag.Parse()
	flag.Visit(func(f *flag.Flag) { isFlagExplicitlySet[f.Name] = true })

	// --- 5. Post-Parse Flag Assignments (for pointers, etc.) ---

	// --- 6. Perform Required Option Checks ---
	initialDefault_Localenumfield := "local-a"
	_, env_Localenumfield_WasSet := os.LookupEnv("ENUM_LOCAL_ENUM")
	initialDefault_Importedenumfield := "option-x"
	_, env_Importedenumfield_WasSet := os.LookupEnv("ENUM_IMPORTED_ENUM")
	if err = func() error { // Required check for unsupported type LocalEnumField (MyLocalEnum) not handled.
	}(); err != nil {
		slog.ErrorContext(ctx, "Error processing required option", "option", "local-enum-field", "error", err)
		os.Exit(1)
	}
	if err = func() error { // Required check for unsupported type ImportedEnumField (customtypes.MyCustomEnum) not handled.
	}(); err != nil {
		slog.ErrorContext(ctx, "Error processing required option", "option", "imported-enum-field", "error", err)
		os.Exit(1)
	}

	// --- 7. Perform Enum Validations ---
	if err = func() error { // Enum validation for unsupported type LocalEnumField (MyLocalEnum) not handled.
	}(); err != nil {
		slog.ErrorContext(ctx, "Error validating enum for option", "option", "local-enum-field", "error", err)
		os.Exit(1)
	}
	if err = func() error { // Enum validation for unsupported type ImportedEnumField (customtypes.MyCustomEnum) not handled.
	}(); err != nil {
		slog.ErrorContext(ctx, "Error validating enum for option", "option", "imported-enum-field", "error", err)
		os.Exit(1)
	}
	if err = func() error { // Enum validation for unsupported type OptionalImportedEnumField (*customtypes.MyCustomEnum) not handled.
	}(); err != nil {
		slog.ErrorContext(ctx, "Error validating enum for option", "option", "optional-imported-enum-field", "error", err)
		os.Exit(1)
	}

	// --- 8. Execute Run Function ---
	err = run(*options)
	if err != nil {
		slog.ErrorContext(ctx, "Runtime error from command function", "error", err)
		os.Exit(1)
	}
}
