package main

import (
	"context"
	"flag"
	"fmt"
	"log/slog"
	"os"

	"github.com/podhmo/goat"
	"github.com/podhmo/goat/examples/enum/customtypes"
)

//go:generate goat emit -run run -initializer NewOptions main.go

// MyLocalEnum is a locally defined enum type.
type MyLocalEnum string

const (
	// LocalA is a possible value for MyLocalEnum.
	LocalA MyLocalEnum = "local-a"
	// LocalB is a possible value for MyLocalEnum.
	LocalB MyLocalEnum = "local-b"
)

var MyLocalEnumValues = []string{
	string(LocalA),
	string(LocalB),
}

// Options defines the command line options for the enum example.
type Options struct {
	// LocalEnumField demonstrates a locally defined enum.
	LocalEnumField MyLocalEnum `env:"ENUM_LOCAL_ENUM"`

	// ImportedEnumField demonstrates an enum imported from another package.
	ImportedEnumField customtypes.MyCustomEnum `env:"ENUM_IMPORTED_ENUM"`

	// OptionalImportedEnumField demonstrates an optional enum (pointer type)
	// imported from another package.
	OptionalImportedEnumField *customtypes.MyCustomEnum `env:"ENUM_OPTIONAL_IMPORTED_ENUM"`
}

// NewOptions initializes Options with default values and enum constraints.
func NewOptions() *Options {
	return &Options{
		LocalEnumField:            goat.Default(LocalA, goat.Enum(MyLocalEnumValues)),                           // Changed
		ImportedEnumField:         goat.Default(customtypes.OptionX, goat.Enum(customtypes.MyCustomEnumValues)), // Changed
		OptionalImportedEnumField: goat.Enum((*customtypes.MyCustomEnum)(nil), []customtypes.MyCustomEnum{customtypes.OptionX, customtypes.OptionY}),
	}
}

// run is the main execution logic for the enum example CLI.
// It prints the selected enum values.
func run(opts Options) error {
	fmt.Printf("Selected Local Enum: %s\n", opts.LocalEnumField)
	fmt.Printf("Selected Imported Enum: %s\n", opts.ImportedEnumField)

	if opts.OptionalImportedEnumField != nil {
		fmt.Printf("Selected Optional Imported Enum: %s\n", *opts.OptionalImportedEnumField)
	} else {
		fmt.Println("Optional Imported Enum: not set")
	}

	// Example of accessing original enum values if needed
	if opts.ImportedEnumField == customtypes.OptionX {
		fmt.Println("INFO: ImportedEnumField is OptionX")
	}

	// Example to trigger an error for testing (e.g. if a certain combination is invalid)
	// if opts.LocalEnumField == LocalA && opts.ImportedEnumField == customtypes.OptionY {
	// 	return fmt.Errorf("combination of LocalA and OptionY is not allowed")
	// }

	return nil
}

// This main function was auto-generated by goat.
func main() {
	ctx := context.Background()
	isFlagExplicitlySet := make(map[string]bool)

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, `enum - run is the main execution logic for the enum example CLI.
         It prints the selected enum values.

Usage:
  enum [flags]

Flags:
  --local-enum-field             mylocalenum LocalEnumField demonstrates a locally defined enum. (required) (env: ENUM_LOCAL_ENUM)
  --imported-enum-field          mycustomenum ImportedEnumField demonstrates an enum imported from another package. (required) (env: ENUM_IMPORTED_ENUM)
  --optional-imported-enum-field mycustomenum OptionalImportedEnumField demonstrates an optional enum (pointer type)
                                        imported from another package. (env: ENUM_OPTIONAL_IMPORTED_ENUM)

  -h, --help                             Show this help message and exit
`)
	}

	var options *Options

	// 1. Create Options using the initializer function.
	options = NewOptions()

	// 2. Override with environment variable values.
	// This section assumes 'options' is already initialized.

	if val, ok := os.LookupEnv("ENUM_LOCAL_ENUM"); ok {

		options.LocalEnumField = MyLocalEnum(val)
	}

	if val, ok := os.LookupEnv("ENUM_IMPORTED_ENUM"); ok {

		options.ImportedEnumField = customtypes.MyCustomEnum(val)
	}

	if val, ok := os.LookupEnv("ENUM_OPTIONAL_IMPORTED_ENUM"); ok {

		typedVal := customtypes.MyCustomEnum(val)
		options.OptionalImportedEnumField = &typedVal
	}

	// 3. Set flags.

	// 4. Parse.
	flag.Parse()
	flag.Visit(func(f *flag.Flag) { isFlagExplicitlySet[f.Name] = true })

	// 5. Perform required checks (excluding booleans).

	// TODO: Implement runtime validation for file options based on metadata:
	// - Check for opt.FileMustExist (e.g., using os.Stat)
	// - Handle opt.FileGlobPattern (e.g., using filepath.Glob)
	// Currently, these attributes are parsed but not enforced at runtime by the generated CLI.

	var err error
	err = run(*options)

	if err != nil {
		slog.ErrorContext(ctx, "Runtime error", "error", err)
		os.Exit(1)
	}
}
