package main

import (
	"context"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"os"
	"slices"
	"strings"

	"github.com/podhmo/goat"
	"github.com/podhmo/goat/examples/enum/customtypes"
)

//go:generate goat emit -run run -initializer NewOptions main.go

// MyLocalEnum is a locally defined enum type.
type MyLocalEnum string

const (
	// LocalA is a possible value for MyLocalEnum.
	LocalA MyLocalEnum = "local-a"
	// LocalB is a possible value for MyLocalEnum.
	LocalB MyLocalEnum = "local-b"
)

var MyLocalEnumValues = []string{
	string(LocalA),
	string(LocalB),
}

// Options defines the command line options for the enum example.
type Options struct {
	// LocalEnumField demonstrates a locally defined enum.
	LocalEnumField MyLocalEnum `env:"ENUM_LOCAL_ENUM"`

	// ImportedEnumField demonstrates an enum imported from another package.
	ImportedEnumField customtypes.MyCustomEnum `env:"ENUM_IMPORTED_ENUM"`

	// OptionalImportedEnumField demonstrates an optional enum (pointer type)
	// imported from another package.
	OptionalImportedEnumField *customtypes.MyCustomEnum `env:"ENUM_OPTIONAL_IMPORTED_ENUM"`
}

// NewOptions initializes Options with default values and enum constraints.
func NewOptions() *Options {
	return &Options{
		LocalEnumField:            goat.Default(LocalA, goat.Enum(MyLocalEnumValues)),                           // Changed
		ImportedEnumField:         goat.Default(customtypes.OptionX, goat.Enum(customtypes.MyCustomEnumValues)), // Changed
		OptionalImportedEnumField: goat.Enum((*customtypes.MyCustomEnum)(nil), []customtypes.MyCustomEnum{customtypes.OptionX, customtypes.OptionY}),
	}
}

// run is the main execution logic for the enum example CLI.
// It prints the selected enum values.
func run(opts Options) error {
	fmt.Printf("Selected Local Enum: %s\n", opts.LocalEnumField)
	fmt.Printf("Selected Imported Enum: %s\n", opts.ImportedEnumField)

	if opts.OptionalImportedEnumField != nil {
		fmt.Printf("Selected Optional Imported Enum: %s\n", *opts.OptionalImportedEnumField)
	} else {
		fmt.Println("Optional Imported Enum: not set")
	}

	// Example of accessing original enum values if needed
	if opts.ImportedEnumField == customtypes.OptionX {
		fmt.Println("INFO: ImportedEnumField is OptionX")
	}

	// Example to trigger an error for testing (e.g. if a certain combination is invalid)
	// if opts.LocalEnumField == LocalA && opts.ImportedEnumField == customtypes.OptionY {
	// 	return fmt.Errorf("combination of LocalA and OptionY is not allowed")
	// }

	return nil
}

// This main function was auto-generated by goat.
func main() {
	ctx := context.Background()
	isFlagExplicitlySet := make(map[string]bool)

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, `enum - run is the main execution logic for the enum example CLI.
         It prints the selected enum values.

Usage:
  enum [flags]

Flags:
  --local-enum-field             mylocalenum LocalEnumField demonstrates a locally defined enum. (default: "local-a") (env: ENUM_LOCAL_ENUM) (allowed: "local-a", "local-b")
  --imported-enum-field          mycustomenum ImportedEnumField demonstrates an enum imported from another package. (default: "option-x") (env: ENUM_IMPORTED_ENUM) (allowed: "option-x", "option-y", "option-z")
  --optional-imported-enum-field mycustomenum OptionalImportedEnumField demonstrates an optional enum (pointer type)
                                        imported from another package. (env: ENUM_OPTIONAL_IMPORTED_ENUM) (allowed: "option-x", "option-y")

  -h, --help                             Show this help message and exit
`)
	}

	// 1. Create Options using the initializer function.
	options := NewOptions()

	// 2. Override with environment variable values.
	// This section assumes 'options' is already initialized.

	if val, ok := os.LookupEnv("ENUM_LOCAL_ENUM"); ok {

		options.LocalEnumField = MyLocalEnum(val)
	}

	if val, ok := os.LookupEnv("ENUM_IMPORTED_ENUM"); ok {

		options.ImportedEnumField = customtypes.MyCustomEnum(val)
	}

	if val, ok := os.LookupEnv("ENUM_OPTIONAL_IMPORTED_ENUM"); ok {

		typedVal := customtypes.MyCustomEnum(val)
		options.OptionalImportedEnumField = &typedVal
	}

	// 3. Set flags.

	if options.OptionalImportedEnumField == nil {
		options.OptionalImportedEnumField = new(customtypes.MyCustomEnum)
	}
	flag.Var(options.OptionalImportedEnumField, "optional-imported-enum-field", `OptionalImportedEnumField demonstrates an optional enum (pointer type)
imported from another package.`)

	// 4. Parse.
	flag.Parse()
	flag.Visit(func(f *flag.Flag) { isFlagExplicitlySet[f.Name] = true })

	// 6. Assign values for initially nil pointers if flags were explicitly set

	// 5. Perform required checks (excluding booleans).

	isValidChoice_LocalEnumField := false
	allowedChoices_LocalEnumField := []string{"local-a", "local-b"}

	currentValue_LocalEnumFieldStr := fmt.Sprintf("%v", options.LocalEnumField)
	isValidChoice_LocalEnumField = slices.Contains(allowedChoices_LocalEnumField, currentValue_LocalEnumFieldStr)

	if !isValidChoice_LocalEnumField {
		var currentValueForMsg interface{} = options.LocalEnumField // options.OptName
		slog.ErrorContext(ctx, "Invalid value for flag", errors.New("Invalid value for flag"), "flag", "local-enum-field", "value", currentValueForMsg, "allowedChoices", strings.Join(allowedChoices_LocalEnumField, ", "))
		os.Exit(1)
	}

	isValidChoice_ImportedEnumField := false
	allowedChoices_ImportedEnumField := []string{"option-x", "option-y", "option-z"}

	currentValue_ImportedEnumFieldStr := fmt.Sprintf("%v", options.ImportedEnumField)
	isValidChoice_ImportedEnumField = slices.Contains(allowedChoices_ImportedEnumField, currentValue_ImportedEnumFieldStr)

	if !isValidChoice_ImportedEnumField {
		var currentValueForMsg interface{} = options.ImportedEnumField // options.OptName
		slog.ErrorContext(ctx, "Invalid value for flag", errors.New("Invalid value for flag"), "flag", "imported-enum-field", "value", currentValueForMsg, "allowedChoices", strings.Join(allowedChoices_ImportedEnumField, ", "))
		os.Exit(1)
	}

	isValidChoice_OptionalImportedEnumField := false
	allowedChoices_OptionalImportedEnumField := []string{"option-x", "option-y"}

	if options.OptionalImportedEnumField != nil {
		currentValue_OptionalImportedEnumFieldStr := fmt.Sprintf("%%v", *options.OptionalImportedEnumField)
		isValidChoice_OptionalImportedEnumField = slices.Contains(allowedChoices_OptionalImportedEnumField, currentValue_OptionalImportedEnumFieldStr)
	} else { // Field is nil

		isValidChoice_OptionalImportedEnumField = true
	}

	if !isValidChoice_OptionalImportedEnumField {
		var currentValueForMsg interface{} = options.OptionalImportedEnumField
		if options.OptionalImportedEnumField != nil {
			currentValueForMsg = *options.OptionalImportedEnumField
		}
		slog.ErrorContext(ctx, "Invalid value for flag", errors.New("Invalid value for flag"), "flag", "optional-imported-enum-field", "value", currentValueForMsg, "allowedChoices", strings.Join(allowedChoices_OptionalImportedEnumField, ", "))
		os.Exit(1)
	}
	if err := run(*options); err != nil {

		slog.ErrorContext(ctx, "Runtime error", "error", err)
		os.Exit(1)
	}
}
