//go:generate goat main.go
package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"log/slog"
	"os"
)

// Options defines the command line options.
type Options struct {
	Version    bool   // Print version information
	Help       bool   // Show help message
	ConfigFile string // Path to the configuration file
}

// run is the actual command logic.
func run(opts Options) error { // Parameter type changed to Options, name to opts
	return json.NewEncoder(os.Stdout).Encode(opts)
}

// This main function was auto-generated by goat.
func main() {
	ctx := context.Background()
	isFlagExplicitlySet := make(map[string]bool)

	flag.Usage = func() {
		fmt.Fprint(os.Stderr, `hello - run is the actual command logic.

Usage:
  hello [flags]

Flags:
  --version     bool     Print version information
  --help        bool     Show help message
  --config-file string   Path to the configuration file (required)

  -h, --help            Show this help message and exit
`)
	}

	// 1. Create Options with default values (no initializer function provided).
	options := new(Options) // options is now a valid pointer to a zeroed struct

	// The following block populates the fields of the options struct.
	// This logic is only executed if no InitializerFunc is provided.

	// 2. Override with environment variable values.
	// This section assumes 'options' is already initialized.

	// 3. Set flags.
	flag.BoolVar(&options.Version, "version", options.Version, "Print version information")
	flag.BoolVar(&options.Help, "help", options.Help, "Show help message")
	flag.StringVar(&options.ConfigFile, "config-file", options.ConfigFile, "Path to the configuration file")

	// 4. Parse.
	flag.Parse()
	flag.Visit(func(f *flag.Flag) { isFlagExplicitlySet[f.Name] = true })

	// 6. Assign values for initially nil pointers if flags were explicitly set

	// 5. Perform required checks (excluding booleans).

	initialDefaultConfigFile := ""
	envConfigFileWasSet := false
	if options.ConfigFile == initialDefaultConfigFile && !isFlagExplicitlySet["config-file"] && !envConfigFileWasSet {
		slog.ErrorContext(ctx, "Missing required flag or environment variable not set", errors.New("Missing required flag or environment variable not set"), "flag", "config-file", "option", "ConfigFile")
		os.Exit(1)
	}

	var err error
	err = run(*options)

	if err != nil {
		slog.ErrorContext(ctx, "Runtime error", "error", err)
		os.Exit(1)
	}
}
